import+export
anaalamed/doc-share-server pull request #18
Opened 2022-11-22 13:13 UTC by talbenzur

2022-11-22 14:16 UTC, LiorMathan94 requested changes

2022-11-22 14:16 UTC, LiorMathan94 commented on src/main/java/docSharing/controller/DocumentEditController.java
> +    public UpdateRequest importFile(String filePath, UpdateRequest updateRequest) {
לא צריך לקבל UpdateRequest

2022-11-22 14:16 UTC, LiorMathan94 commented on src/main/java/docSharing/controller/DocumentEditController.java
> +    public UpdateRequest exportFile(UpdateRequest updateRequest) {
לא צריך UpdateRequest

2022-11-22 14:16 UTC, LiorMathan94 commented on src/main/java/docSharing/service/DocumentService.java
> +    public void exportFile(String content){
צריך לקבל:
1. document ID
2. את הנתיב לקובץ שבו ישמור את התוכן

public void export(int documentId, String filename)

2022-11-22 14:16 UTC, LiorMathan94 commented on src/main/java/docSharing/service/DocumentService.java
> +    public void exportFile(String content){
ואז הפונקציה הזאת תשמור לקובץ את התוכן של המסמך שיש לו את ה-ID הזה.

2022-11-22 14:16 UTC, LiorMathan94 commented on src/main/java/docSharing/service/DocumentService.java
> +    public String importFile(String path){
צריך לקבל את הנתיב לקובץ שממנו רוצים לקרוא:
public Document import(String filename)

ואז בפונקציה: יוצרים מסמך חדש, קוראים את התוכן שיש בקובץ filename, ושמים במסמך שיצרנו את התוכן שקראנו.
שומרים את המסמך הזה בDB ומחזירים אותו.

2022-11-22 14:24 UTC, talbenzur commented on src/main/java/docSharing/service/DocumentService.java
> +    public void exportFile(String content){
public UpdateRequest exportFile( String filename,
                                    UpdateRequest updateRequest) {
        String content = updateRequest.getContent();
        documentService.exportFile(content, filename);
        return updateRequest;
    }
    
    לדעתך סבבה? 
    
    כאילו אני מעדיפה לקבל את התוכן של המסמך והוא נמצא בupdaterequest

2022-11-22 14:27 UTC, talbenzur commented on src/main/java/docSharing/service/DocumentService.java
> +    public String importFile(String path){
אני מקבלת את file path במקום filename. הוא כולל בתוכו את השם ומאפשר לי גישה ישירה למסמך. 

אחלה, אעשה שמירה לDB.

2022-11-27 07:01 UTC, LiorMathan94 requested changes

2022-11-27 07:20 UTC, LiorMathan94 approved these changes

2022-11-27 07:20 UTC, merged