Document controller
anaalamed/doc-share-server pull request #8
Opened 2022-11-20 14:19 UTC by talbenzur

2022-11-20 14:50 UTC, LiorMathan94 requested changes

2022-11-20 14:50 UTC, LiorMathan94 commented on src/main/java/docSharing/controller/FolderController.java
> +        if(!isCreateValid(owner, title)) {
לעשות את הבדיקות כאן ולפרט את ההודעה המתאימה

2022-11-20 14:50 UTC, LiorMathan94 commented on src/main/java/docSharing/utils/Utils.java
> +    public static boolean isCreateValid(User owner, String title) {
הפונקציה הזאת לא מספיק ברורה וגם לא כל כך מתאימה לutils...

2022-11-20 15:01 UTC, talbenzur commented on src/main/java/docSharing/utils/Utils.java
> +    public static boolean isCreateValid(User owner, String title) {
הורדתי אותה, העברתי את הבדיקות ישירות בcontroller

2022-11-20 15:01 UTC, talbenzur commented on src/main/java/docSharing/controller/FolderController.java
> +        if(!isCreateValid(owner, title)) {
fixed

2022-11-21 09:05 UTC, LiorMathan94 approved these changes

2022-11-21 09:05 UTC, merged